# Generated by Django 5.2.8 on 2025-11-14 20:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boat',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boatattachment',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='navigationroute',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.AllObjectsManager()),
                ('active_objects', core.models.ActiveManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='work',
            managers=[
                ('objects', core.models.ActiveManager()),
                ('all_objects', core.models.AllObjectsManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='DNI/NIE'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
