# Generated by Django 5.2.8 on 2025-11-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_managers_alter_boat_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatattachment',
            name='file_url',
        ),
        migrations.AddField(
            model_name='boatattachment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='boat_attachments/'),
        ),
    ]
