# Generated by Django 5.2.8 on 2025-11-16 12:03

from django.db import migrations
def create_initial_roles(apps, schema_editor):
    UserRole = apps.get_model('core', 'UserRole')
    UserRole.objects.get_or_create(name="Account Owner")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_boatattachment_file_url_boatattachment_file'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles),
    ]
