# Generated by Django 5.2.8 on 2025-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_initial_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
    ]
