# Generated by Django 5.2.8 on 2025-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_document_file_url_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatattachment',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='boatattachment',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
