# Generated by Django 5.2.8 on 2025-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_boatattachment_options_boatattachment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
