# Generated by Django 5.2.8 on 2025-11-29 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_work_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_companies', to='core.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='core_accoun_account_e14ef9_idx'), models.Index(fields=['company'], name='core_accoun_company_4c329a_idx')],
                'unique_together': {('account', 'company')},
            },
        ),
    ]
