# Generated by Django 5.2.8 on 2025-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accountcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationpoint',
            name='type',
            field=models.CharField(choices=[('gps', 'GPS Tracking'), ('start', 'Start Point'), ('end', 'End Point'), ('stop', 'Stop/Anchor')], default='gps', max_length=20),
        ),
        migrations.AlterField(
            model_name='navigationpoint',
            name='recorded_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
